@startuml
hide circles
skinparam ClassAttributeIconSize 0
hide interface fields

Class Cesar{
    -key: int
    +encode(self: encryptor_cesar_t *, message: const char *, result: const char *): int
    +decode(message: String): String
}

Class Vigenere{
    -key: String
    +encode(self: encryptor_cesar_t *, message: const char *, result: const char *): int
    +decode(message: String): String
}

Class RC{
    -key: String
    +encode(self: encryptor_cesar_t *, message: const char *, result: const char *): int
    +decode(message: String): String
}

Class Encryptor{
    +encode(self: encryptor_cesar_t *, message: const char *, result: const char *): int
    +decode(message: String): String
}

Class Socket{
    
}

Cesar ..|> Encryptor
Vigenere ..|> Encryptor
RC ..|> Encryptor

@enduml
